# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeAi < Formula
  desc "Forge workflow CLI for AI agents"
  homepage "https://github.com/robsonferr/forgeai"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_darwin_x86_64.tar.gz"
      sha256 "5c1b384a53f8780a7656aa4f5869e43ef0cda623ab06b2b1dc346e59525a0027"

      define_method(:install) do
        bin.install "forge-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_darwin_arm64.tar.gz"
      sha256 "39cfc4f07e777b1f6e732cfd4124fca1f4e45c96f1d594f0ddd018a7a74a6da7"

      define_method(:install) do
        bin.install "forge-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_linux_x86_64.tar.gz"
      sha256 "cc0f44b9122c1415ab2f0543cefc5979f1f4b4237f394a4bdf0d3039633be356"
      define_method(:install) do
        bin.install "forge-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_linux_arm64.tar.gz"
      sha256 "8e4eac95f45032c9604fdd930c31f18ef331819e4da2d80127d2c77b1e69e8af"
      define_method(:install) do
        bin.install "forge-ai"
      end
    end
  end

  test do
    system "#{bin}/forge-ai", "--version"
  end
end
