# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeAi < Formula
  desc "Forge workflow CLI for AI agents"
  homepage "https://github.com/robsonferr/forgeai"
  version "0.4.1-snapshot"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.4.0/forge-ai_0.4.1-snapshot_darwin_x86_64.tar.gz"
      sha256 "d3fc54cef025f983b50baa8b6bada5f881485543148c0e6b380a1f0e409d93e5"

      define_method(:install) do
        bin.install "forge-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.4.0/forge-ai_0.4.1-snapshot_darwin_arm64.tar.gz"
      sha256 "b9ac0b08d35c6d053ec2b3275e30ad9867ed2c766bd43f3700b0bfbd96afc9f1"

      define_method(:install) do
        bin.install "forge-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.4.0/forge-ai_0.4.1-snapshot_linux_x86_64.tar.gz"
      sha256 "c7b6ea64526d558f583c7a1b33741c0e1049f9a8c742729bad9c9090d0777ef1"
      define_method(:install) do
        bin.install "forge-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.4.0/forge-ai_0.4.1-snapshot_linux_arm64.tar.gz"
      sha256 "f690fd93fa01af3c4679b33d2725effe6520b0191a073c3b17ce79fc669cf847"
      define_method(:install) do
        bin.install "forge-ai"
      end
    end
  end

  test do
    system "#{bin}/forge-ai", "--version"
  end
end
