# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ForgeAi < Formula
  desc "Forge workflow CLI for AI agents"
  homepage "https://github.com/robsonferr/forgeai"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_darwin_x86_64.tar.gz"
      sha256 "cfa3b647f4f137b500da1524a5d30af5ba5198971037e414d707a7e0437c5893"

      define_method(:install) do
        bin.install "forge-ai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_darwin_arm64.tar.gz"
      sha256 "aa0f92bbdea4b692ed16a5cedaf3ace51c6e2e3bad41b3548d2a6c23a1f2136b"

      define_method(:install) do
        bin.install "forge-ai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_linux_x86_64.tar.gz"
      sha256 "da0380f780da20f9c4046be992c01b8d8eeb2e6c85d17e0734cf900e13c2ec52"
      define_method(:install) do
        bin.install "forge-ai"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robsonferr/forgeai/releases/download/v0.5.0/forge-ai_0.5.0_linux_arm64.tar.gz"
      sha256 "762c95f996f40eef6b7b337a476632659208f1cd6cef3230655c7c617316f269"
      define_method(:install) do
        bin.install "forge-ai"
      end
    end
  end

  test do
    system "#{bin}/forge-ai", "--version"
  end
end
